### ISSUE TITLE
Displacement filter repeated

### ISSUE THREAD

**Issue by PixelsCommander** [pixijs/pixi.js#1795]
Hi

Wondering why do my DisplacementFilter repeats in this scene http://pixelscommander.com/polygon/ripples/demo/ripples.html . Scene and code are very similar to official example, mostly copypasted.

**Comment by englercj** [comment]
Good question, I'm not 100% sure since it is hard to tell with all the extra stuff going on.

Is there a chance of getting a minimal example of this bug in a jsfiddle? A focused test case makes it much easier to drill into the problem.

**Comment by PixelsCommander** [comment]
Sure, here you are http://pixelscommander.com/polygon/ripples/demo/ripples-simple.html

**Comment by PixelsCommander** [comment]
@GoodBoyDigital , @englercj 

Hi guys, is there a chance to get some workaround for this today?

I tried to find one by myself but failed.

The reason I am asking for help today is that displacement scaling is very important for demo I am going to show at PhoneGap Day Europe tomorrow. It is going to be a great marketing for Pixi as well as for HTML GL.

**Comment by PixelsCommander** [comment]
Figured out it depends on image used for filter. Image from displacement map demo works better but still repeats to the left.

**Comment by GoodBoyDigital** [comment]
hey there! quick fix for now - make your displacement texture non power of two and it should stop tiling :)

**Comment by PixelsCommander** [comment]
:+1: The problem is solved, we may close the ticket.

**Comment by englercj** [comment]
Going to keep it open because it is definitely a bug, just has a workaround. Has to do with the filters we setup for the texture based on size.

**Comment by Shurikov** [comment]
1233


Воскресенье, 17 мая 2015, 7:00 -07:00 от Denis Radin <notifications@github.com>:
>The problem is solved, we may close the ticket.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Илья Шурикоа
ilkom5@mail.ru

**Comment by Prinzhorn** [comment]
> hey there! quick fix for now - make your displacement texture non power of two and it should stop tiling :)

The documentation explicitly says "The texture used for the displacement map. Must be power of 2 sized texture.". The official demo (http://pixijs.github.io/examples/index.html?s=filters&f=displacement-map.js&title=Displacement Map) uses a 500x250 texture even though the actual circle is 150x150 (http://pixijs.github.io/examples/_assets/displace.png) and is still buggy, see screenshot (the artefacts left of the ring)

![screenshot-pixi-displacement](https://cloud.githubusercontent.com/assets/679144/10303719/fd5f6138-6c15-11e5-8222-f49e3df8c931.png)

I wonder why the demo has this random spacing around the circle which is not accounted for in the code? Maybe it was chosen to make the demo since it masks the non-functional implementation? If I crop the circle out it repeats, even though it is 150x150, which is not a power of two.

There seem to be even more issues with the displacement filter. Depending on the size of the filter there's a point after which a bigger scale factor (displacementFilter.scale.x/y) will linearly scale _the whole background_ which should not be affected at all.

It'd be sick if you could fix the displacement filter. There are multiple open issues. Maybe if you point me in the right direction I can help. I guess the problem is not the filter itself (https://github.com/pixijs/pixi.js/tree/master/src/filters/displacement) but the way filters are set up in general?

**Comment by goldenratio** [comment]
any update on the tiling issue? :)

**Comment by ivanpopelyshev** [comment]
@goldenratio what problem do you have exactly?

**Comment by goldenratio** [comment]
If I use displacement map of 512x512 tiling happens. Workaround is to use map of 513x513

**Comment by goldenratio** [comment]
Upgraded to Pixi.js v 3.0.11 - same issue

**Comment by ivanpopelyshev** [comment]
Sorry, v3 is not supported anymore. Please move to v4.

Anyway, workaround for v3, i just commented a section. Please put this before you create the renderer:

```js
WebGLRenderer.prototype.updateTexture = function (texture)
{
    texture = texture.baseTexture || texture;

    if (!texture.hasLoaded)
    {
        return;
    }

    var gl = this.gl;

    if (!texture._glTextures[gl.id])
    {
        texture._glTextures[gl.id] = gl.createTexture();
        texture.on('update', this.updateTexture, this);
        texture.on('dispose', this.destroyTexture, this);
        this._managedTextures.push(texture);
    }


    gl.bindTexture(gl.TEXTURE_2D, texture._glTextures[gl.id]);

    gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, texture.premultipliedAlpha);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, texture.source);

    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, texture.scaleMode === CONST.SCALE_MODES.LINEAR ? gl.LINEAR : gl.NEAREST);


    if (texture.mipmap && texture.isPowerOfTwo)
    {
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, texture.scaleMode === CONST.SCALE_MODES.LINEAR ? gl.LINEAR_MIPMAP_LINEAR : gl.NEAREST_MIPMAP_NEAREST);
        gl.generateMipmap(gl.TEXTURE_2D);
    }
    else
    {
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, texture.scaleMode === CONST.SCALE_MODES.LINEAR ? gl.LINEAR : gl.NEAREST);
    }

    if (!texture.isPowerOfTwo)
    {
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    }
    /*else
    {
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.REPEAT);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.REPEAT);
    }*/

    return  texture._glTextures[gl.id];
};
```

**Comment by chrisjj** [comment]
This appears to be the same issue as subsequently acknowledged as a bug here https://github.com/pixijs/pixi.js/issues/4039?_pjax=%23js-repo-pjax-container and fixed.

**Comment by ivanpopelyshev** [comment]
@chrisjj 

there are two modes: REPEAT and CLAMP_TO_EDGE. In v4, it depends whether or not texture is pow2. 

#4039 is about CLAMP+touching the edge. This issue is about sudden REPEAT when texture is pow2. Neither were fixed.

**Comment by chrisjj** [comment]
Thanks. #4039 looks fixed to me.
