### ISSUE TITLE
Can't get RenderTexture to work with mask

### ISSUE THREAD

**Issue by ShayDavidson** [pixijs/pixi.js#3473]
Hey, I'm trying in v4 to get a texture of a masked graphic by another graphic, using this piece of code:

```js
const container = new PIXI.Container()
const item = getBaseGraphic()
const mask = getMaskGraphic()
item.mask = bites
container.addChild(item)
container.addChild(mask)
const renderTexture = PIXI.RenderTexture.create(256, 256)
renderer.render(container, renderTexture)
return renderTexture
```

The problem is the texture is empty as long as I apply a mask on `item`. If I comment out the `mask` assignment, I get the texture but without the mask - just the 2 graphics on top of each other.

I'm using the `WebGLRenderer`.

Any idea what am I doing wrong?

**Comment by staff0rd** [comment]
are you able to supply a [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by GoodBoyDigital** [comment]
Hi @ShayDavidson, this should be fixed now on the dev branch 👍

**Comment by ShayDavidson** [comment]
@GoodBoyDigital the funny thing is that I'm just writing the pen 😆

**Comment by Patrick-Hammond** [comment]
I'm experiencing this issue on PIXI 4.3.4 (and the latest dev branch) on an Android device (Lenovo Yoga Book).
fiddle: http://jsfiddle.net/5mydwyxd/7/
this WebGl error occurs:
[.Offscreen-For-WebGL-0xdd06d000]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete (check)

**Comment by GoodBoyDigital** [comment]
hi @Patrick-Hammond! can you try with the latest dev branch please? cheers!

**Comment by Patrick-Hammond** [comment]
okay, just built the latest sources and tested and it still happens :(

**Comment by GoodBoyDigital** [comment]
sweet, was that a fresh update? we updated the pixi-gl-core package a couple of days ago. ta!

**Comment by Patrick-Hammond** [comment]
hi, i see in my node modules that pixi-gl-core is version 1.0.3 and your latest on github is 1.1.0
when I run npm install it doesn't update :( 
in pixi's package.json the dependancy is "pixi-gl-core": "^1.0.3"
should that also be 1.1.0 ?

**Comment by GoodBoyDigital** [comment]
could you try that pls?

**Comment by Patrick-Hammond** [comment]
so I deleted the pixi-gl-core and it retrieved the latest (1.1.0) after install :)
unfortunately i still get the same errors when running on the Android device (Lenovo Yoga Book)

**Comment by GoodBoyDigital** [comment]
cool thanks for taking a look! I have a galaxy tab 4 i can test on :)

**Comment by Patrick-Hammond** [comment]
Hi again,
One of our devices is also a galaxy tab 4 and it doesn't show the error unfortunately.
The last PIXI release to work on the Yoga Book was 4.3.2 and when I added this change: [#3545](https://github.com/pixijs/pixi.js/pull/3545/files) it causes the error.
We have about 15 Android devices for testing and the Lenovo Yoga Book is the only one that has this issue. It also does something strange when creating renderTextures, rather than being empty (transparent) on creation, it is filled black.
Just saying this because perhaps it is something odd that this device is doing rather than PIXI.
Cheers!

**Comment by ivanpopelyshev** [comment]
@Patrick-Hammond 

It seems that you are using rectangle masks. There's workaround: use

```
var voidFilter = new PIXI.filters.VoidFilter();

//for every mask
container.filters = [voidFilter ];
//absolute coordinates! position does not affect them!
container.filterArea = new PIXI.Rectangle(100, 100, 200, 200);
```

**Comment by Patrick-Hammond** [comment]
@ivanpopelyshev 

Thanks! that's a good workaround for me.

**Comment by ivanpopelyshev** [comment]
@Patrick-Hammond 

That's faster than a regular mask but slower than scissor. I use it for many things, like layering: http://pixijs.github.io/examples/#/layers/lighting.js

**Comment by jdelrue** [comment]
This seems to be still an issue on the latest version. This small examples shows it:

```
var app = new PIXI.Application(800, 600, {backgroundColor: 0x1099bb});
document.body.appendChild(app.view);

var basicText = new PIXI.Text('Basic text in pixi is very long');
basicText.x = 30;
basicText.y = 90;

var mask = new PIXI.Graphics();
mask.drawRect(0,90,500,20);

basicText.mask = mask; // turn on or off

  var renderTexture = PIXI.RenderTexture.create(app.screen.width, app.screen.height);

  app.renderer.render(basicText, renderTexture);

  let sprite1 = new PIXI.Sprite(renderTexture);

//app.stage.addChild(basicText); // turn on or off
app.stage.addChild(sprite1); // turn on or off
````

**Comment by jdelrue** [comment]
> @Patrick-Hammond
> 
> It seems that you are using rectangle masks. There's workaround for it:
> 
> ```js
> var voidFilter = new PIXI.filters.VoidFilter();
> 
> //for every mask
> container.filters = [voidFilter ];
> //absolute coordinates! position does not affect them!
> container.filterArea = new PIXI.Rectangle(100, 100, 200, 200);
> ```

Tried this, however there seems a few pixels of difference between the two methods:

```
var app = new PIXI.Application(800, 600, {backgroundColor: 0x1099bb});
document.body.appendChild(app.view);

//apply mask to basictext
var basicText = new PIXI.Text('Basic text in pixi is very long');
basicText.x = 0;
basicText.y = 0;

var mask = new PIXI.Graphics();
mask.drawRect(0,0,500,15);

basicText.mask = mask;

//apply voidfilter (alphafilter..) to second basictext 50px lower
var basicText2 = new PIXI.Text('Basic text in pixi is very long');
basicText2.x = 0;
basicText2.y = 50;

var voidFilter = new PIXI.filters.VoidFilter();
basicText2.filters = [voidFilter ];
basicText2.filterArea = new PIXI.Rectangle(0,50,500,15);


//add both

app.stage.addChild(basicText); // turn on or off
app.stage.addChild(basicText2); // turn on or off
```

**Comment by molst** [comment]
Howdi,

What's the status on this one? I'm experiencing the same problem while using rounded rect masks with holes in it in menu layouts (using th new holes API in v5), so I guess the workaround wouldn't work for me..
