### ISSUE TITLE
Masking breaks render to rendertexture

### ISSUE THREAD

**Issue by jdelrue** [pixijs/pixi.js#5321]
As seen in following example you cannot render to a texture when a mask is set: 

```
var app = new PIXI.Application(800, 600, {backgroundColor: 0x1099bb});
document.body.appendChild(app.view);

var basicText = new PIXI.Text('Basic text in pixi is very long');
basicText.x = 30;
basicText.y = 90;

var mask = new PIXI.Graphics();
mask.drawRect(0,90,500,20);

basicText.mask = mask; // turn on or off

  var renderTexture = PIXI.RenderTexture.create(app.screen.width, app.screen.height);

  app.renderer.render(basicText, renderTexture);

  let sprite1 = new PIXI.Sprite(renderTexture);

//app.stage.addChild(basicText); // turn on or off
app.stage.addChild(sprite1); // turn on or off

```

**Comment by ivanpopelyshev** [comment]
dev or v4.x?

i think i fixed that already in both

**Comment by ivanpopelyshev** [comment]
ok, its graphics:

```
mask.beginFill(0xffffff, 1)
mask.drawRect(0,90,500,20);
```

masking works with fills.

**Comment by jdelrue** [comment]
Thanks, works now. Is this intended behavior or workaround? Seems like workaround to me?

**Comment by jdelrue** [comment]
@ivanpopelyshev I still have a big problem with this. If you define a mask before rendering a texture, there is a BIG memory leak. Without a mask there is no problem.
```
var app = new PIXI.Application(800, 600, {backgroundColor: 0x1099bb});
document.body.appendChild(app.view);
for(var i=0;i<1000;i++){
    var basicText = new PIXI.Text('Basic text in pixi is very long');
    basicText.x = 30;
    basicText.y = 90;

    var mask = new PIXI.Graphics();
    mask.drawRect(0,90,500,20);
    mask.beginFill(0xffffff, 1)
    basicText.mask = mask; // turn on or off

    var renderTexture = PIXI.RenderTexture.create(app.screen.width, app.screen.height);

    app.renderer.render(basicText, renderTexture);

    let sprite1 = new PIXI.Sprite(renderTexture);

    app.stage.addChild(sprite1); // turn on or off
    sprite1.destroy({ children: true, texture: true, baseTexture: true });
}
```

**Comment by ivanpopelyshev** [comment]
You didnt mention which version and which browser do you use.

Itested it on 4.8.4 (release) and yes, i see consumed GPU memory, however pixi calls `deleteTexture` and `deleteFramebuffer` for all those elements, so its not our fault.

**Comment by jdelrue** [comment]
Chrome 
Version 66.0.3359.181 (Official Build) (64-bit)

The difference between with and without masking is so high my program is unusable....

**Comment by angiagia** [comment]
I have encountered a lot of resource-consuming masks, you should limit the use of masks because it takes a lot of resources for rendering. In some cases I use another way to create masks and reduce a lot of memory compared to when using masks.
You can refer to:
https://pixijs.io/examples/#/demos/mask-render-texture.js
Hope it will be helpful.
Read more about mask perfomance in: 
https://github.com/pixijs/pixi.js/wiki/v4-Performance-Tips

**Comment by ivanpopelyshev** [comment]
ok, so, basically, renderTexture that uses masks costs more. In your case there are many renderTextures, i dont know why aren't they destroyed, pixi calls `destroyTexture` for sure, so it consumes more memory.

@GoodBoyDigital ideas?

**Comment by ivanpopelyshev** [comment]
@jdelrue try this build please: https://pixijs.download/dev-renderbuffer-destroy/pixi.js

**Comment by bigtimebuddy** [comment]
Let us know if this didn’t fix the problem. Closing after Ivan’s PR seems to have fixed.

**Comment by jdelrue** [comment]
Thanks works now! What a team :+1:
