### ISSUE TITLE
pixi.js 5.1.5 - "Cannot read property 'start' of undefined"

### ISSUE THREAD

**Issue by dranitski** [pixijs/pixi.js#6171]
My working project stopped working after updating to pixi.js@5.1.5

Steps to reproduce:

1. git clone https://dmitrydranitski@bitbucket.org/dmitrydranitski/pixijs-5.1.1-5.1.5-update-bug.git
2. cd into dir
3. npm i
4. npm run dev 
5. go to the url (https://localhost:8080 by default)
you should see the page
![image](https://user-images.githubusercontent.com/27373393/66823580-3dcfe380-ef4f-11e9-8b4f-7e7758bc7241.png)
6. Ctrl+C - stop the webpack-dev-server
7. rm -rf node_modules
8. npm i pixi.js@5.1.5
9. npm run dev 
10. go to the url (https://localhost:8080 by default)
11. The code is not working. I can not see the reason, seems like a bug?
![image](https://user-images.githubusercontent.com/27373393/66823619-4a543c00-ef4f-11e9-8a20-599ff98f49ad.png)

Thanks in advance for any help!

- **`pixi.js` version**: 5.1.1 (working) - 5.1.5 (not working)
- **Browser & Version**: Version 76.0.3809.100 (Official Build) (64-bit)
- **OS & Version**: Arch Linux

**Comment by ivanpopelyshev** [comment]
> Known bug.  Two versions of pixi exist at the same time, renderers are registered in only one of them.

> "Remove package.lock and node_modules" helps.

We have a number of threads in forums & here, all closed.

I dont know personally what to do about it, except "throw webpack away, use vanilla js!"

**Comment by dranitski** [comment]
"Remove package.lock and node_modules" helped. Thanks!

**Comment by stevemarksd** [comment]
I run `yarn remove pixi.js-legacy` and fixed it. I think the `pixi.js-legacy` module messes up with the regular pixi. Or maybe the versions of pixi and pixi.js-legacy don't match. Didn't had time to investigate.

**Comment by hellmark1990** [comment]
It happened again. 

I had the following dependencies in my package.json:
`
"pixi-filters": "3.1.1",
"pixi.js": "5.2.2"
`

- New 5.2.3 pixi.js version has been released. 
- I still have "pixi.js": "5.2.2" as a dependency. 
- After `npm install` some pixi.js dependencies in package-lock.json are pointed to 5.2.3 some are still to 5.2.2.

Solution in my case:
- Update my pixi.js dependency to 5.2.3
- Clear node_modules and package-lock.json
- npm install
- Now all pixi.js dependencies are pointed to 5.2.3 versions, so there are no versions conflict now and issue is solved.

**Comment by MarkTDSUltra** [comment]
![Screenshot 2021-02-22 at 13 09 00](https://user-images.githubusercontent.com/69678730/108712755-26274880-750f-11eb-8960-8e1f9277237f.png)

**Comment by adilmas13** [comment]
I'm facing the same issue after updating to Pixi v6.0.0. Cleared node_modules and package-lock.json and reinstalled all the dependency. Still no luck... 
Can any one help out ?

**Comment by DiBuz** [comment]
I faced the same problem in version 6.0.0. An example of my code https://codesandbox.io/s/test-pixi-v6-momwd

**Comment by elliotbradly** [comment]
Happening here as well. Guess I roll back to v5.

**Comment by elliotbradly** [comment]
Yup. That worked.

**Comment by hec-lopz** [comment]
I had the same issue with v6.2.0. I downgraded to v6.1.3 and it worked.

**Comment by TrevorSundberg** [comment]
For anyone who ran into this issue, did some debugging and found that one potential cause was due to:
```ts
Renderer.registerPlugin("batch", BatchRenderer);
```

In my particular case, it's because I was trying to reduce size and removed the import to `pixi.js` and instead started importing each module, such as `@pixi/core` etc. By not importing `pixi.js` I was missing the `registerPlugin` calls, as well as several other plugins.

**Comment by maitrungduc1410** [comment]
remove node_modules and package-lock.json helped

**Comment by devexus** [comment]
I have similar problem.
![image](https://user-images.githubusercontent.com/47736308/174124067-ca9c3d47-6efb-4b7b-9fe4-74d2f2897fa0.png)
I created library with react components based on webpack. I registered all required plugins:
`
Renderer.registerPlugin("batch", BatchRenderer);

Renderer.registerPlugin("interaction", InteractionManager);

Application.registerPlugin(AppLoaderPlugin);

Application.registerPlugin(TickerPlugin);
`
When I open [storybook](https://storybook.js.org/) everything works correctly, but when I build it on github actions and install in react app pixi displays black screen. 

![image](https://user-images.githubusercontent.com/47736308/174125333-a2201abd-7ec9-4a5d-9ee2-ab177005a29c.png)
Any ideas what can be wrong? How can I solve it?

**Comment by sd-ditoy** [comment]
Just want to add that i could not get pixi.js to work above ^6.0.0 in a brand new Vue 2.6 project.
Just did `npm install pixi.js` and added the default/recommended import for the new instance:
```
import * as PIXI from 'pixi.js';
```

Which would cause the same error as described above, as soon as i call `render()`.
I just went back to 5.3.12 instead.

I really think you should investigate this. If the first experience users have, is this, i wouldn't be surprised if most jump ship, which would be regrettable.

**Comment by AlinaAndriychuk** [comment]
I had the same issue when I was updating pixi to 6.5.8 version and building it by modules (not installing the whole pixi.js or pixi.js-legacy but installing it like:
```
    "@pixi/app": "6.5.8",
    "@pixi/constants": "6.5.8",
    "@pixi/core": "6.5.8",
    "@pixi/display": "6.5.8",
    "@pixi/extensions": "6.5.8",
    "@pixi/graphics": "6.5.8",
    "@pixi/math": "6.5.8",
    "@pixi/mesh-extras": "6.5.8",
    "@pixi/settings": "6.5.8",
    "@pixi/sprite": "6.5.8",
    "@pixi/text": "6.5.8",
    "@pixi/utils": "6.5.8"
```
    
**The reason of this error**: "Cannot read property 'start' of undefined" was not adding full pixi like "pixi.js" or "pixi.js-legacy" to the project.
When in whole my project was no "pixi.js" import like `import {Point} from "pixi.js"` - this issue happened.

When we create the new Application like this:
```
        new Application({
            backgroundAlpha: 0,
            antialias: true,
            width: window.innerWidth,
            height: window.innerHeight,
            autoDensity: true,
            resolution: window.devicePixelRatio || 1
        });
``` 
It creates Renderer to render the stage - every object that is in canvas.
But for rendering Renderer needs the "batch" plugin.
When we install the full pixi.js it is there by default. You can check it in any Renderer.
<img width="981" alt="Screenshot 2022-12-01 at 16 49 42" src="https://user-images.githubusercontent.com/69072889/205083559-99d522c7-e72c-47e7-8877-ed3d7cc0652d.png">
But when we do not import "pixi.js" or "pixi.js-legacy" in the whole project and use only its modules (to optimise project size for example) - the plugins property is empty. And when the Renderer tries to render - it can't find the batch plugin and this issue happens.

**The solution**: We need to add batch plugin. (As [TrevorSundberg](https://github.com/TrevorSundberg) said) 
For pixi version below 6.5.0 use
`Renderer.registerPlugin("batch", BatchRenderer);`
If your pixi version is upper as mine use this:

```
      // install "@pixi/core" and "@pixi/extensions" packages
      
      import {BatchPluginFactory} from "@pixi/core";
      import {extensions, ExtensionType} from "@pixi/extensions";

       const BatchRenderer = BatchPluginFactory.create();
        extensions.add({
            name: 'batch',
            ref: BatchRenderer,
            type: ExtensionType.RendererPlugin,
        });
```

I could explain something wrong, and will be glad if you will correct me.
Hope this will help someone.

**Comment by chittebabu21** [comment]
I am using Pixi 8.1.0 and am having issue with rendering the image. I have no issues with drawing rectangles or circles, only with images it does not render. I am using a try catch block below.

`try {
        Assets.add('bg', 'bg-10001.png');
        const textures = await Assets.load('bg');
        app.stage.addChild(textures);
    } catch (e) {
        console.log(e);
    }`

The error is logged out: `TypeError: Cannot read properties of undefined (reading 'startsWith')
    at checkDataUrl (checkDataUrl.mjs:9:15)
    at Object.test (loadTextures.mjs:54:81)
    at eval (Resolver.mjs:329:26)
    at Array.forEach (<anonymous>)
    at eval (Resolver.mjs:323:14)
    at Array.forEach (<anonymous>)
    at eval (Resolver.mjs:322:17)
    at Array.forEach (<anonymous>)
    at Resolver.add (Resolver.mjs:310:16)
    at AssetsClass.add (Assets.mjs:152:19)`

Any help will be appreciated. I do not wish to roll back to previous versions of Pixi and the image path is correct. Have also tried deleting node_modules and package.lock.json and reinstalling again but still no success.
