### ISSUE TITLE
SVG Image on Pixi.js renders very blurry

### ISSUE THREAD

**Issue by confile** [pixijs/pixi.js#936]
I tested pixi.js with an SVG image and it turns out that rendering is not very good. I created a showcase jsfiddle here: 

http://jsfiddle.net/confile/w84y9k7c/

Is there a way to get better SVG rendering with Pixi.js?

**Comment by okrad** [comment]
+1

**Comment by englercj** [comment]
Reopening this since people obviously want it, but not putting it on a milestone yet.

**Comment by mariussmit** [comment]
+1

**Comment by tadfmac** [comment]
+1

**Comment by fwojciechowski** [comment]
+1

**Comment by fuchsnj** [comment]
+1

**Comment by meekgeek** [comment]
+1

**Comment by nodecode** [comment]
+1

**Comment by Philoozushi** [comment]
+1

**Comment by benjaminmcdonald** [comment]
+1

**Comment by robinisaksson** [comment]
+1

**Comment by hexxen** [comment]
+1

**Comment by ZARk-be** [comment]
+1

**Comment by holographix** [comment]
+1

**Comment by iandanforth** [comment]
:+1:

**Comment by englercj** [comment]
If anyone wants to write a v3 plugin for this, I'd be happy to help out with it. We have some other awesome plugins we will be making first, so this may be a while unless the community takes it up to do it!

**Comment by nym** [comment]
+1

**Comment by jwdunn1** [comment]
+1

**Comment by pauser** [comment]
We are using this https://github.com/gabelerner/canvg for SVG usage and it does the job very well.
You have 
scaleWidth: int => scales horizontally to width
scaleHeight: int => scales vertically to height
that help you define the size of the canvas and using toDataURL() you will get the base64 image.

**Comment by saschagehlich** [comment]
+1 for real SVG on WebGL

**Comment by sebastianseelig** [comment]
+1 for real SVG support on WebGL

**Comment by hugofqueiros** [comment]
+ 1

**Comment by saschagehlich** [comment]
I've been working on an SVG to PIXI.Graphics conversion thingy for the past couple of hours and it works pretty well:

https://github.com/saschagehlich/pixi-svg-graphics

You can see a demo here:
http://filshmedia.net/lab/pixi-svg/
(The PIXI.Container is scaled up to 10x (original SVG is like 80x80), and it's still crispy)

It's not fully implemented yet, but I tried it with a couple of SVG files and I think this is a good start. Unfortunately complex geometry does not work right now, but I'll look into that within the next couple of days.

If anyone wants to help out - feel free to contribute. :)

**Comment by thepian** [comment]
+1

loads of assets in games don't really fit then notion of everything is a raster

**Comment by paos** [comment]
+1

**Comment by Lokidottir** [comment]
+1

**Comment by saschagehlich** [comment]
My PIXI-SVG-Graphics project now supports complex paths, making it useable. Also, I published it as a module on npm: https://www.npmjs.com/package/pixi-svg-graphics

**Comment by FlorianLudwig** [comment]
I would prefer a solution that leverages the browsers SVG render engine instead of implementing a new render engine.

My idea would be to create a subclass of Sprite (and/or BaseTexture) "SVGSprite".  If the webGL renderer is used, the svg must be rendered to a texture in the displayed size so it does not get blurry.

The idea:
 * create a 2d canvas in the exact size that is needed for the webgl renderer
 * use .drawImage(svg_file,0, 0); on the 2d canvas
 * use the 2d canvas as texture for the webGL renderer

The size must be determined using the global transformation matrix so the scale is correct computed even when the SVGSprite is insied a scaled container.  The SVGSprite must have an update function so the calculation and source canvas is redone.

This way all SVG features the browser supports work in pixi and the result is non-blurry.

**Comment by caffeineaddiction** [comment]
@FlorianLudwig so something like https://gist.github.com/biovisualize/8187844 used with `PIXI.Texture.fromCanvas` with some way of of updating the canvas version of the image if an attribute of the SVG changed like `mySVG.setAttribute("transform", "scale(50 50)");`?

**Comment by Quentie** [comment]
+1

**Comment by makc** [comment]
@saschagehlich 
> My PIXI-SVG-Graphics project now supports complex paths, making it useable.

it looks like [basic things are still missing](https://github.com/saschagehlich/pixi-svg-graphics/issues/5)?

**Comment by makc** [comment]
This kind of code
```javascript
	var canvas = document.createElement ('canvas');
	canvas.width = ...; canvas.height = ...;
	canvas.getContext ('2d').drawImage (svgImage, 0, 0, canvas.width, canvas.height);

	var sprite = new PIXI.Sprite (new PIXI.Texture (new PIXI.BaseTexture (canvas)));
```
allows to create the sprite with required resolution without altering svg (except if you want to stretch it, then you must add `preserveAspectRatio="none"` to svg tag).

**Comment by darve** [comment]
+1

**Comment by wizche** [comment]
+1

**Comment by kelfman** [comment]
+1

**Comment by Channely** [comment]
+1

**Comment by mantolo** [comment]
+1

**Comment by foxoo7** [comment]
+1

**Comment by Ansien12** [comment]
+1

**Comment by cherifGsoul** [comment]
+1

**Comment by shawnrushefsky** [comment]
+1

**Comment by Shurikov** [comment]
+1

**Comment by OutThisLife** [comment]
+1

**Comment by samrm111** [comment]
+1

**Comment by cozmy** [comment]
+1

**Comment by englercj** [comment]
If you wish to "+1" this issue, please use GitHub Reactions to +1 the original post. I will start deleting the +1s in this thread as it is just noise and makes it impossible to read conversation here.

**Comment by makc** [comment]
on the other hand, if github reactions do not "bump" the thread or email annoying notifications to the team, what's the point of using them :) could as well write "like" on the piece of paper and flush it down the toilet

**Comment by RanzQ** [comment]
I modified the Texture code to support this, the 4th parameter takes a scale for the svg, like this:

```
new PIXI.Texture.fromImage('bunny.svg', undefined, undefined, 2.0);
```

I forked the bunnymark and you can play with the scale by changing line 66 from JS here:
http://codepen.io/anon/pen/pyXMzR.

@englercj, I can create a PR if this looks ok: https://github.com/RanzQ/pixi.js/commit/07522e6dddcdb4741e196ad5f20bb8e534fbb59e

**Comment by RanzQ** [comment]
PR: https://github.com/pixijs/pixi.js/pull/2614

**Comment by englercj** [comment]
PR merged, closing this!

**Comment by trusktr** [comment]
@englercj That PR only scales the texture, it doesn't really add real SVG support (as in a Graphics hierarchy representation of the SVG), which would be super nice! This would be similar to @saschagehlich's idea, but he didn't PR that as a feature to add in Pixi.

Can you re-open this as wishing to have real SVG support?

**Comment by ova2** [comment]
It works good in Chrome und FF, but doesn't work in IE11. I got SecurityError with this line of code

```
let tiger = new Sprite(new PIXI.Texture.fromImage('images/tiger.svg', true, PIXI.SCALE_MODES.LINEAR, 8.0)); 
```

![image](https://user-images.githubusercontent.com/767334/33979635-8db9a558-e0a5-11e7-87f3-7c64182578d7.png)

**Comment by saschagehlich** [comment]
Ah the good ol' SecurityError. That's a bug in IE11 that has been fixed in Edge, but not in IE11: 

https://github.com/pixijs/pixi.js/issues/2928

There's nothing you can do, except converting your SVG to PNG

**Comment by ova2** [comment]
Good to know. Thanks for hint.

Am 14.12.2017 08:10 schrieb "Sascha Gehlich" <notifications@github.com>:

**Comment by dentez** [comment]
I'm trying to use PIXI.Texture.fromImage to display a SVG image like you explained above, but on a smartphone the SVG seems blurry. 

Here a sample code [https://codepen.io/anon/pen/QaxqvP](https://codepen.io/anon/pen/QaxqvP)
On desktop browser it seems ok, but when I try this on my smartphone or android emulator the SVG renders like this:
[https://imgur.com/VbXlypP](https://imgur.com/VbXlypP)  (image on the left is PIXI-SVG; right, is an html img tag).

Maybe It is something with devicePixelRatio, it seems that the browser "Zooms-in" to fit the screen - since on desktop if I zoom-in I can emulate the same behavior.
How is the correct way to show/scale SVG on a device with pixel ratio bigger than 1?

**Comment by psyrendust** [comment]
Doesn’t look blurry to me. Screenshot is from an iPhone X.

**Comment by dentez** [comment]
Zoom in your screenshot,  you will see it. Your is less blurry than mine but it is blurry.

**Comment by maximedupre** [comment]
I'm trying the example above, but for some reason,

    let texture = new PIXI.Texture.fromImage('../assets/heart.svg', false, undefined, 2);

throws

    ERROR Error: The SVG image must have width and height defined (in pixels), canvas API needs them.

If I load the image first with

    PIXI.loader.add("../assets/heart.svg").load(...)

The error isn't thrown, but the rendered sprite that contains the texture from `new PIXI.Texture.fromImage` is all pixelated, which makes me believe the SVG isn't rendered correctly. Furthermore, changing the `sourceScale` seems to have no effect.

**Comment by RanzQ** [comment]
@maximedupre due to browser limitations, only px values work. That's why the error is thrown so that you know you need to modify your svgs.
